name: Delete Snapshot
description: Deletes a specified RDS snapshot.

inputs:
  snapshot_id:
    description: 'The ID of the snapshot to delete.'
    required: true
  snapshot_region:
    description: 'Region where placed RDS snapshot.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Delete RDS snapshot
      shell: bash
      run: |
        aws rds delete-db-snapshot \
          --db-snapshot-identifier ${{ inputs.snapshot_id }} \
          --region ${{ inputs.snapshot_region }}
